version: "3"

services:
  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/var/lib/postgresql/data
  server:
    build:
      context: ./../..
      dockerfile: ./docker/dev/Dockerfile
    image: unsynced/compass:latest
    command: bash -l -c "./docker/dev/init.sh; npm run dev"
    volumes:
      - ./../..:/opt/node/app
      - /opt/node/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres@database/compass
    depends_on:
      - database

volumes:
  postgres:
